# Generated by Django 4.0.4 on 2022-04-15 20:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_neighbourhood_profile_bio_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='picture'),
        ),
    ]
