# Generated by Django 4.0.4 on 2022-04-17 10:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='App.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='hood_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hood_logo'),
        ),
    ]
